name: CirrOS builder

on:
  push:
    branches:
      - master

jobs:
  build-cirros-aarch64:
    name: aarch64
    runs-on: ubuntu-18.04
    env:
      ARCHES: aarch64
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily
  
  build-cirros-arm:
    name: arm
    runs-on: ubuntu-18.04
    env:
      ARCHES: arm
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily

  build-cirros-i386:
    name: i386
    runs-on: ubuntu-18.04
    env:
      ARCHES: i386
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily

  build-cirros-x64_64:
    name: x86_64
    runs-on: ubuntu-18.04
    env:
      ARCHES: x86_64
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily

  build-cirros-powerpc:
    name: powerpc
    runs-on: ubuntu-18.04
    env:
      ARCHES: powerpc
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily

  build-cirros-ppc64:
    name: ppc64
    runs-on: ubuntu-18.04
    env:
      ARCHES: ppc64
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily

  build-cirros-ppc64le:
    name: ppc64le
    runs-on: ubuntu-18.04
    env:
      ARCHES: ppc64le
      BOOTTEST: "true"
      QUIET: 1
    steps:
      - name: Pull CirrOS artifacts
        uses: actions/checkout@v3

      - name: Build CirrOS
        shell: bash
        run: |
          sudo apt-get install -y cloud-utils qemu-system openbios-ppc
          ./bin/system-setup
          ./bin/build-release daily
